package br.ufrn.imd;                           	//00 []
public class TestLinearCode {                  	//01 [00]
    public static void main(String[] args) {   	//02 [01]
        System.out.println("Starting");        	//03 [02]
        int a, b;                              	//04 [03]
        System.out.println("Quem");          	//05 [04]
        System.out.println("me");          		//06 [05]
        System.out.println("dera");        		//07 [06]
        System.out.println("ser");        		//08 [07]
        System.out.println("um");       		//09 [08]
        System.out.println("peixe");       		//10 [09]
        int c, d;								//11 [10]
        int e, f;                               //12 [11]
        System.out.println("para");        		//13 [12]
        System.out.println("em");        		//14 [13]
        System.out.println("seu");      		//15 [14]
        System.out.println("límpido");      	//16 [15]
        System.out.println("aquário");       	//17 [16]
        System.out.println("mergulhar");       	//18 [17]
        System.out.println("...");       		//19 [18]
        System.out.println("...");       		//20 [19]
        int g, h;                               //21 [20]
        int i, j;                               //22 [21]
        int k, l;                               //23 [22]
    }
}