package br.ufrn.imd.optmalg.model;

public enum StatementType {
    METHOD_DECLARATION, VAR_DECLARATION, IF, ELSE, FOR, WHILE,
    DO_WHILE_OPEN, DO_WHILE_CLOSE, RETURN, BREAK, CONTINUE, SWITCH, CASE,
    TRY, CATCH, FINALLY, UNKNOWN
}